[DRAFT] RadioGroup Component
Programmer-Network/yail pull request #24
Opened 2024-05-05 22:24 UTC by smadixd

2024-05-11 22:03 UTC, agjs requested changes
Overall, looks amazing. For faster PR's and more clarity, I'd always suggest to include a screenshot or a video of a feature. This is to say, only when we are talking about the UI components.

2024-05-11 22:03 UTC, agjs commented on src/Components/Inputs/RadioGroup/index.tsx
> +            key={`${index}`}
You can get rid of template literal :-).

2024-05-11 22:03 UTC, agjs commented on src/Components/Inputs/RadioGroup/RadioGroup.stories.tsx
>        options={[
Let's maybe user faker for the RadioGroup options, e.g. take a look at the `Accordion` stories. This is just so we can dynamically generate various different lengths of strings, and see how the components looks like.

2024-05-11 22:03 UTC, agjs commented on .eslintcache
> +[{"G:\\repo\\opensource\\yail\\src\\Components\\Inputs\\RadioGroup\\RadioGroup.stories.tsx":"1","G:\\repo\\opensource\\yail\\src\\Components\\Inputs\\RadioGroup\\index.tsx":"2","G:\\repo\\opensource\
Let's remove this from the PR, maybe you have done that already in the following PR's.

What I'd suggest at stages like this, feel free to get into interactive rebase and squash things. At this point, this can be a single commit PR.

2024-05-13 20:04 UTC, smadixd commented on src/Components/Inputs/RadioGroup/RadioGroup.stories.tsx
>        options={[
![image](https://github.com/Programmer-Network/yail/assets/49820024/6a2ceb13-2024-4186-89c6-86f8678765d8)

2024-05-13 21:07 UTC, closed without merging